export const styles: { [key: string]: React.CSSProperties } = {
    page: {
      fontFamily: "Arial, sans-serif",
      minHeight: "100vh",
      background: "#f5f6fa",
    },
    roomImageContainer: {
      width: "100%",
      marginTop: "20px",
      height: "150px",
      borderRadius: 8,
      overflow: "hidden",
      boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
      // transition: "transform 0.3s, box-shadow 0.3s",
      cursor: "pointer",
    },
    roomImage: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      display: "block",
      transition: "transform 0.3s",
    },
   
    logoutBtn: {
      padding: "6px 12px",
      borderRadius: 6,
      border: "none",
      background: "#ff4d4f",
      color: "#fff",
      cursor: "pointer",
    },
    main: {
      display: "flex",
      padding: 30,
      gap: 20,
    },
    sidebar: {
      minWidth: 200,
    },
    sidebarBox: {
      background: "#fff",
      padding: 20,
      borderRadius: 12,
      boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
      marginBottom: 20,
    },
    sectionTitle: {
      marginBottom: 15,
      color: "#555",
      fontSize: 16,
      fontWeight: 600,
    },
    createLink: {
      display: "block",
      background: "#007bff",
      color: "#fff",
      padding: "10px 12px",
      borderRadius: 8,
      border: "none",
      textAlign: "center",
      textDecoration: "none",
      marginBottom: 10,
      width: "90%",
      cursor: "pointer",
    },
    profileInfo: {
      fontSize: 14,
      color: "#555",
      marginTop: 5,
    },
    mainContent: {
      flex: 1,
    },
    mainTitle: {
      marginBottom: 20,
      color: "#333",
      fontSize: 20,
      fontWeight: 600,
    },
    roomGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
      gap: 20,
    },
    roomCard: {
      background: "#fff",
      borderRadius: 12,
      padding: 20,
      boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
      transition: "transform 0.2s, box-shadow 0.2s",
      cursor: "pointer",
      display: "flex",
      flexDirection: "column",
      justifyContent: "space-between",
    },
    roomCardHover: {
      transform: "translateY(-5px)",
      boxShadow: "0 8px 20px rgba(0,0,0,0.15)",
    },
    roomTitle: {
      margin: 0,
      fontSize: 18,
      color: "#333",
    },
    roomCapacity: {
      margin: "8px 0",
      color: "#777",
      fontSize: 14,
    },
    roomStatus: {
      display: "inline-block",
      padding: "5px 20px",
      borderRadius: 8,
      fontSize: 12,
      fontWeight: 500,
    },
    roomBtn: {
      flex: 1,
      padding: "6px 0",
      borderRadius: 8,
      border: "none",
      cursor: "pointer",
    },
    editBtn: {
      background: "#007bff",
      color: "#fff",
    },
    deleteBtn: {
      background: "#ff4d4f",
      color: "#fff",
    },
  };